futures_util::future::MapErr<impl futures_util::Future<Output = std::result::Result<(), std::io::Error>>, {closure@src\service\file_manager.rs:42:50: 42:53}>
